TA#50667 [IMP] partner_duplicate_mgmt : hide standard action menu for merging contact
Numigi/odoo-partner-addons pull request #100
Opened 2023-03-07 11:00 UTC by lanto-razafindrabe

2023-03-10 02:50 UTC, majouda requested changes

2023-03-10 02:50 UTC, majouda commented on partner_duplicate_mgmt/security/res_groups.xml
> +            <field name="name">Restricted accessibility</field>
Hello @lanto-razafindrabe peux tu changer avec un titre plus significatif. 
Sachant que le groupe sera affiché sur le vue user. Il faut qu'un utilisateur sache qu'il faut pas cocher ce groupe. 

Exemle "Show native partner merge action"

2023-03-10 02:50 UTC, majouda commented on partner_duplicate_mgmt/__manifest__.py
> +        'views/res_partner_merge_action_hidden.xml',
Il faut updater la version du module pour forcer la mise à jour du module.

2023-03-10 09:11 UTC, lanto-razafindrabe commented on partner_duplicate_mgmt/__manifest__.py
> +        'views/res_partner_merge_action_hidden.xml',
Ok d'accord

2023-03-10 09:12 UTC, lanto-razafindrabe commented on partner_duplicate_mgmt/security/res_groups.xml
> +            <field name="name">Restricted accessibility</field>
Je vais suivre ton exemple dans ce cas. merci

2023-03-13 15:08 UTC, majouda approved these changes

2023-03-13 15:08 UTC, merged