Add modules partner_validation, partner_validation_sale/purchase
Numigi/odoo-partner-addons pull request #32
Opened 2018-11-22 14:43 UTC by apollet

Add modules partner_validation, partner_validation_sale, partner_validation_sale

2018-11-25 01:31 UTC, foutoucour commented
Salut @apollet ,

Merci pour le travail si rapide.
Les outils de CI et de code analysis ont des soucis avec les forks.
J'ai réglé le comportement de circleci. Une nouvelle PR devrait permettre aux tests de rouler.
Je continue à voir pour codacy.

Jordi

2018-11-26 02:11 UTC, foutoucour commented
Salut @apollet 

Les liens avec les intégrations sont rétablies.

Merci de ton travail.
Jordi

2018-11-26 14:47 UTC, apollet commented
salut @foutoucour ,
Le build plante sur un autre module.
Et les erreurs de qualité n'en sont pas vraiment pour moi, es-tu d'accord ?

2018-11-26 14:48 UTC, ddufresne commented
@apollet merci, je vais regarder ça ce matin.

2018-11-26 15:41 UTC, ddufresne commented
@apollet j'ai corrigé l'erreur du build. Peux-tu rebaser stp?

aussi, stp ajouter tes 3 modules aux 2 endroits suivants:

- ./Dockerfile
- ./.docker_files/main/__manifest__.py

attention à l'ordre alphabétique des modules. merci!

2018-11-26 17:57 UTC, ddufresne requested changes

2018-11-26 17:57 UTC, ddufresne commented on partner_validation/models/res_partner_restricted_field.py
> +        domain=_get_model_domain, required=True)
ça pourrait simplemment être domain="[('model_id.model', '=', 'res.partner')]"

2018-11-26 17:57 UTC, ddufresne commented on partner_validation/views/res_partner_restricted_field.xml
> +                <filter string="Archived" name="inactive" domain="[('active','=',False)]"/>
Un filtres pour voir les éléments archivés est ajouté automatiquement par Odoo. Pas besoin de l'ajouter dans le XML.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/i18n/fr.po
> +msgstr "Permission to change the state of the partner denied."
oups, la traduction est en anglais aussi ;)

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +            mapped('name')
display_name au lieu de name stp

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +        return super(PurchaseOrder, self).button_confirm()
mineur, on peut écrire sous la forme super().button_confirm() en python 3

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +    def check_state_access(self):
ici, il y a un conflit de nom avec la fonctionnalité équivalente dans partner_validation_sale.

Stp, renommer la méthode pour check_supplier_state_access.
Faire la modification équivalente dans le module partner_validation_sale.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +        self.check_state_access()
Pas besoin d'avoir les droits d'accès pour confirmer ou rejeter un partenaire.
Seule l'approbation requiert des droits particuliers.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +            restricted_suppliers = self.filtered(lambda p: p.supplier and p.supplier_state in ('confirmed', 'approved'))
La contrainte doit seulement être levée si le partenaire est à l'état approved.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +                                " when the partner’s status is confirmed/approved" % str(final_restricted_fields)))
Dans le ticket de spec, le message est:

You are not authorized to modify the following fields: [insérez les champs] when
the partner’s status is approved.

pas confirmed/approved

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/tests/test_purchase_order.py
> +        self.assertEqual(self.purchase_order.state, 'draft')
pourrais-tu séparer tes méthodes de test stp?

ici, tu testes 2 concepts différents dans la même méthode.

1. la confirmation avec normal_user
2. la confirmation avec supplier_approval_user

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/tests/test_purchase_order.py
> +        self.assertEqual(self.purchase_order.state, 'draft')
séparer ceci en 3 méthodes de test.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/tests/test_res_partner.py
> +            self.partner.sudo(self.normal_user).reject_customer()
valider un élément par méthode stp

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/tests/test_res_partner.py
> +        self.assertEqual(self.partner.customer_state, 'confirmed')
même chose

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/tests/test_sale_order.py
> +        self.assertEqual(self.sale_order.state, 'draft')
même commentaire que pour achats.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/tests/test_stock_picking.py
> +            self.fail("button_validate() raised ExceptionType unexpectedly!")
même commentaire pour les tests de ce fichier.

Une validation par méthode.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/tests/test_stock_picking.py
> +            self.fail("button_validate() raised ExceptionType unexpectedly!")
aussi, un try, except dans un test unitaire, c'est très inhabituel. Une erreur remontée devrait être systématiquement prévisible.
je préfère with assertRaises

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                <div>
Les boutons ainsi que le champ supplier_state doivent apparaître seulementsi le partenaire est un partenaire commercial.

Un partenaire commercial correspond à ['|', ('is_company','=', True), ('parent_id', '=', False)]

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/views/res_partner.xml
> +                        groups="partner_validation_sale.group_partner_restricted_field_sales">
même commentaire que pour la partie fournisseur.
Ces éléments ne doivent apparaître que si le partenaire est un partenaire commercial.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +            self.check_state_access()
La vérification d'accès ne doit pas être faite si la valeur contenue dans vals n'est pas `approved`.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/res_partner.py
> +        if 'customer_state' in vals:
La vérification d'accès ne doit pas être faite si la valeur contenue dans customer_state n'est pas `approved`.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/sale_order.py
> +            mapped('name')
mapped('display_name') stp

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/stock_picking.py
> +                mapped('name')
mapped('display_name') stp

2018-11-26 17:57 UTC, ddufresne commented on partner_validation/__manifest__.py
> +    'author': 'Akretion',
Svp, changer l'auteur pour Numigi.

Ajouter un README à chaque module. Tu peux te baser sur le README d'un autre de nos modules sur le repo.
Ajouter Akretion dans la section Contributors du README.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation/__init__.py
> +# -*- coding: utf-8 -*-
enlever les # -*- coding: utf-8 -*-

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +                            " in order to confirm this purchase order." % str(restricted_partners)))
On ne veut pas voir les crochets ouvrants et fermants "[". On veut seulement le nom du partenaire.

![image](https://user-images.githubusercontent.com/27902736/49031610-78cefa00-f178-11e8-94e3-8284a1d8c100.png)

The supplier Ready Mat has to be approved...

ps: sur le screenshot, je suis en Odoo v12, mais le travail était bien à faire en v11 ;)

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +        string='Supplier State', readonly=True, default='new')
track_visibility='onchange'

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/res_partner.py
> +        string='Customer State', readonly=True, default='new')
track_visibility='onchange'

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +        if not self.env.user.has_group('partner_validation_purchase.group_partner_restricted_field_purchases'):
La validation des champs ne doit être faite que pour un partenaire commercial.

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/sale_order.py
> +            filtered(lambda p: p.customer and p.customer_state != 'approved').\
filtered(lambda p: p.customer_state != 'approved').\

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_sale/models/stock_picking.py
> +                filtered(lambda p: p.customer and p.customer_state != 'approved').\
filtered(lambda p: p.customer_state != 'approved').\

2018-11-26 17:57 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +            filtered(lambda p: p.supplier and p.supplier_state != 'approved').\
filtered(lambda p: p.supplier_state != 'approved').\

2018-11-26 19:11 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:11 UTC, ddufresne commented on partner_validation_sale/tests/test_res_partner.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/tests/test_stock_picking.py
> +        except:
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [No exception type(s) specified](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_purchase/tests/test_purchase_order.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/tests/test_sale_order.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/models/res_partner.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_purchase/tests/test_res_partner.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/tests/test_stock_picking.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/models/stock_picking.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-26 19:12 UTC, ddufresne commented on partner_validation_sale/models/sale_order.py
> +from odoo.exceptions import Warning
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Redefining built-in 'Warning'](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-27 13:40 UTC, apollet commented on partner_validation/views/res_partner_restricted_field.xml
> +                <filter string="Archived" name="inactive" domain="[('active','=',False)]"/>
J'ai testé sans sur une v11 community et cela ne l'ajoute pas automatiquement donc je l'ai laissé

2018-11-27 13:41 UTC, ddufresne commented on partner_validation/models/res_partner_restricted_field.py
> +from odoo import fields, models, api
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused api imported from odoo](https://app.codacy.com/app/numigi/odoo-partner-addons/pullRequest?prid=2609146)

2018-11-27 13:42 UTC, ddufresne commented on partner_validation/views/res_partner_restricted_field.xml
> +                <filter string="Archived" name="inactive" domain="[('active','=',False)]"/>
ok

2018-11-27 14:04 UTC, ddufresne requested changes
@apollet merci pour les correctifs :+1: 

seulement un petit détail non bloquant que j'aimerais éclaircir.

2018-11-27 14:04 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
@apollet pourquoi la div vide?

2018-11-27 14:04 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
pourrais-tu commenter l'explication dans le xml stp?

2018-11-27 14:08 UTC, apollet commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
@ddufresne pour faire joli (vraiment), sinon l'affichage des boutons n'est pas très beau

2018-11-27 14:18 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
@apollet vaudrait mieux une classe css pour ça alors.

2018-11-27 14:23 UTC, apollet commented
@foutoucour 
Les tests qui ne passent pas ne sont pas dans les nouveaux modules.
Quand je lance les tests de partner_duplicate_mgmt sur ma machine, ce ne sont pas les mêmes tests qui sont en erreur...
Sur une BDD fraiche mes tests passent.
Ceux de partner_duplicate_mgmt ne passent pas si le mudule purchase est installé (à cause du champ purchase_line_warn sur les product_template qui vient du module purchase)
-> psycopg2.IntegrityError: null value in column "purchase_line_warn" violates not-null constraint

2018-11-27 14:28 UTC, ddufresne commented
@apollet je vais arranger les 3 tests en erreur et regarder pour purchase_line_warn.

2018-11-27 14:38 UTC, ddufresne commented
@apollet concernant ton erreur

> psycopg2.IntegrityError: null value in column "purchase_line_warn" violates not-null constraint

Elle se produit seulement si tu lances les tests de odoo en lançant un vrai serveur odoo avec --test-enable. Nous utilisons pytest-odoo: https://github.com/camptocamp/pytest-odoo. Ça évite ce genre d'erreur qui n'a aucun lien avec le module développé.

Tu peux facilement rouler les tests avec:

docker-compose run --rm odoo pytest /mnt/extra-addons

2018-11-27 17:42 UTC, ddufresne commented
@apollet les tests sont corrigés, tu peux rebaser. merci

2018-11-28 14:40 UTC, apollet commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
C'est fait ;)

2018-11-28 15:03 UTC, ddufresne requested changes

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_sale/views/res_partner.xml
> +                        groups="partner_validation_sale.group_partner_restricted_field_sales">
le groupe d'utilisateur est seulement requis pour l'action Confirm

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                        groups="partner_validation_purchase.group_partner_restricted_field_purchases">
Le groupe est seulement requis pour l'action Approve

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_sale/models/sale_order.py
> +                                " in order to confirm this sale order." % (",".join(restricted_partners))))
Ici, la traduction ne fonctionne pas

![image](https://user-images.githubusercontent.com/27902736/49159372-5fea5400-f2f2-11e8-9b69-15b7db61fe59.png)

le problème est au niveau des parenthèses

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_sale/models/stock_picking.py
> +                                    " to confirm this stock move." % (",".join(restricted_partners))))
même chose ici, cette traduction ne fonctionnera pas

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_purchase/models/purchase_order.py
> +                                " in order to confirm this purchase order." % (",".join(restricted_partners))))
même chose ici, cette traduction ne fonctionnera pas

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +                                    " when the partner’s status is approved" % str(final_restricted_fields)))
même chose ici, cette traduction ne fonctionnera pas

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_sale/models/res_partner.py
> +                                    " when the partner’s status is approved" % str(final_restricted_fields)))
même chose ici, cette traduction ne fonctionnera pas

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_purchase/models/res_partner.py
> +                                    " when the partner’s status is approved" % str(final_restricted_fields)))
aussi, il manque un point à la fin de la phrase

2018-11-28 15:03 UTC, ddufresne commented on partner_validation_sale/views/res_partner.xml
> +                <div class="custom_div_button_sale" attrs="{'invisible': ['|', '|', ('customer','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
sur un contact sans société parente, les boutons n'apparaissent pas alors qu'ils le devraient

![image](https://user-images.githubusercontent.com/27902736/49160479-d38d6080-f2f4-11e8-8841-24de8f52cff7.png)

2018-11-28 15:38 UTC, ddufresne commented on partner_validation_purchase/views/res_partner.xml
> +                <div attrs="{'invisible': ['|', '|', ('supplier','=', False), ('is_company','=', False), ('parent_id', '=', True)]}">
cool, merci

2018-11-28 15:54 UTC, apollet commented on partner_validation_sale/views/res_partner.xml
> +                        groups="partner_validation_sale.group_partner_restricted_field_sales">
Cela rentre en conflit avec ce que tu m'a demander la derniere fois:
> Pas besoin d'avoir les droits d'accès pour confirmer ou rejeter un partenaire.
> Seule l'approbation requiert des droits particuliers.

Tu veux peut être parler de l'action Approve ?

2018-11-28 15:56 UTC, ddufresne commented on partner_validation_sale/views/res_partner.xml
> +                        groups="partner_validation_sale.group_partner_restricted_field_sales">
@apollet oui, désolé, je voulais bien parler de Approve.

2018-11-29 09:50 UTC, apollet commented
@ddufresne 
J'ai corrigé les domains et les groups sur la vue partner mais pour les traductions je n'y arrive pas...je ne comprend pas pourquoi cela ne fonctionne pas alors que de mémoire cela fonctionnait au premier commit.
Si tu as la solution je suis preneur.

2018-11-29 13:37 UTC, ddufresne commented
@apollet concernant les traductions, par exemple pour celle-ci

raise WarningOdoo(_("You are not authorized to modify the following fields: %s"
                                    " when the partner’s status is approved." % str(final_restricted_fields)))

tu peux réécrire de cette manière:

raise WarningOdoo(_("You are not authorized to modify the following fields: %s"
                                    " when the partner’s status is approved.") % str(final_restricted_fields))

C'est de déplacer une parenthèse pour que les paramètres soient injectés une fois le terme traduit.

2018-11-29 13:46 UTC, apollet commented
@ddufresne merci, c'est corrigé :)

2018-11-29 13:50 UTC, ddufresne commented
@apollet cool merci, je fais un dernier tour de vérification, mais à mon avis, ça devrait être nickel.

2018-11-29 13:56 UTC, ddufresne approved these changes
@apollet merci pour les correctifs. LGTM

2018-11-29 13:57 UTC, merged