TA#34372 partner_industry_tree_view module
Numigi/odoo-partner-addons pull request #81
Opened 2021-07-20 15:26 UTC by gabgosrob

2021-07-21 00:13 UTC, ddufresne requested changes
@gabgosrob j'ai l'impression que tu as copié un module existant et oublié de le renommer.

Le module n'a pas de lien avec les secteurs (industry).

2021-07-21 18:59 UTC, gabgosrob commented
> @gabgosrob j'ai l'impression que tu as copié un module existant et oublié de le renommer.
> 
> Le module n'a pas de lien avec les secteurs (industry).

Ah oui, je pensais au début que le champ à mettre était industry_id et j'ai oublié de changer le nom.

2021-07-26 09:50 UTC, ddufresne requested changes

2021-07-26 09:50 UTC, ddufresne commented on partner_city_tree_view/README.rst
> +This module adds the industry sector field to the partner tree view.
@gabgosrob il faut ajuster le README stp

2021-07-26 09:50 UTC, ddufresne commented on partner_city_tree_view/__manifest__.py
> +    "summary": "Adds the industry sector to the partner tree view.",
Ajuster le manifest aussi

2021-07-26 14:30 UTC, ddufresne approved these changes

2021-07-26 14:30 UTC, merged